project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!drafts/"

website:
  title: "Karim K. Kardous"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
format:
  html:
    theme:
      - cosmo
      - brand
    css: nyt_theme.css
    highlight-style: github-dark


