project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!drafts/"
   # - "!projects/finance-dashboard/"  # this excludes any projects from being rendered (say when they're still work in progress)
website:
  site-url: https://kkardousk.github.io/
  site-path: /
  
  page-navigation: true
  
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    title: "Karim K. Kardous"  
    contents:
      - section: "Navigation"
        contents:
          - href: index.qmd
            text: Home
          - href: about.qmd
            text: About
          - href: projects/nhs-healthcare/tom-calver-article-NHS.qmd
            text: "Is NHS Good Value?"
          # - href: projects/finance-dashboard/dashboard_starter.qmd 
          #   text: "Stock Market Analysis & Forecast"       
          - href: projects/travel-tourism/holder-chokshi-granados-article-TravelToUS.qmd
            text: "Intl. Travel Into the US"
          - href: projects/mathematics-inversions/inversions_py/inversions_py.qmd
            text: "Inversions and their interesting properties"
          - href: projects/mathematics-inversions/inversions_py/koch_snowflake_fractals.qmd
            text: "Koch and his Snowflakes, Fractals"
          - href: projects/journalism-gaza/journalism_and_political_violence.qmd
            text: "The state of Journalism in Gaza"
          - href: https://huggingface.co/spaces/kardouskarim/gaza-damage-assessments
            text: 'Gaza Damage Assessment Shiny App (2025)'
            target: "_blank"
          - href: projects/sept11-legacy/sept11_legacy.qmd
            text: "The 9/11 Legacy"
      - section: "Older Links"
        contents:
          - href: https://github.com/kkardousk/aoe
            text: 'Age of Empires Replay Parser (2022)'
            target: "_blank"
          - href: https://www.kaggle.com/code/karimkardous/restaurant-business-in-2020-in-us/notebook
            text: 'Restaurant Business in 2020 (2021)'
            target: "_blank"
          - href: https://www.researchgate.net/publication/283755253_Vindicating_the_Ubiquitous_Rationality_in_Civil_War_Violence_a_Redirection_from_Macro_to_Microdynamics_of_Civil_War_Violence
            text: 'Vindicating the Rationality in Civil War Violence (2016)'
            target: "_blank"
          - href: https://www.researchgate.net/publication/298642701_Dynamics_of_Democratic_Breakdown_Macro-Comparative_Evidence_of_Golpes_de_Estado_and_Autogolpes_from_Latin_America
            text: 'Dynamics of Democratic Breakdown in Latin America (2016)'
            target: "_blank"
          - href: https://www.researchgate.net/publication/287646067_What_Causes_Civil_Wars_Competing_Risks_Analyses_of_worldwide_Civil_War_Onsets_between_1970_and_1999
            text: 'What Causes Civil Wars: Competing Risks Analyses (2016)'
            target: "_blank"
          - href: https://scispace.com/pdf/explaining-the-dynamics-of-civil-war-exposure-violence-and-26p0q7cze2.pdf
            text: "Master's Thesis: Explaining the Dynamics of Civil War Exposure & Violence (2016)"
            target: "_blank"
   
  page-footer:
    left: "© 2025 Karim K. Kardous"
    right:
      - icon: github
        href: https://github.com/kkardousk
format:
  html:
    theme:
      light: [cosmo, custom.scss]
    css: styles.css
    highlight-style: github-dark
    toc: false
    code-fold: true
    embed-resources: true