project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!drafts/"

website:
  title: "Karim K. Kardous"
  site-url: https://kkardousk.github.io/
  site-path: /
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: tom-calver.qmd
        text: "Is NHS Good Value ? (Replication)"
      # - href: has-international-travel-to-the-us-really-collapsed.qmd
      #   text: "Has International Travel to the U.S. Really Collapsed ? (Replication)"

format:
  html:
    theme:
      - cosmo
      - brand
    css: nyt_theme.css
    highlight-style: github-dark
    toc: true
    code-fold: true
    embed-resources: true  