---
title: ""
---

<div class="header-banner">
  <h1>Where Data Meets Curiosity</h1>
  <p class="lead">I explain my thought process (once I understand my own brain), feel free to check out my data replication, visualizations, and analysis projects I like to do in my spare time - also feel free to connect with me if you have any questions or suggestions; proceed with caution !</p>
</div>

## Recent Projects

<div class="project-card">
  <h3 class="project-title">Is NHS Good Value? (Replication)</h3>
  <p>Replication of a data-driven article/analysis of the UK's healthcare systems among other countries; by British editor Tom Calver</p>s
  <a href="tom-calver-article-NHS.qmd" class="btn btn-primary">View Project</a>
</div>

<!-- You can add more project cards here as you develop more content -->

## About This Site

This personal website serves as a repository for my data analysis projects, replications of interesting studies, and explorations of topics that spark my curiosity. As a data enthusiast, I enjoy diving into datasets, uncovering insights, and sharing my findings.
